#!/bin/sh
#
# Script to run a sql file in a single transaction such that it halts and rolls back on the first error.
# Source: https://petereisentraut.blogspot.com/2010/03/running-sql-scripts-with-psql.html 
#

set -euo pipefail

usage() {
   echo "Script for running a SQL script file in a single transaction with rollback on error."
   echo "   Usage: $0 username dbname hostname sql-file"
}

if [ -z "${1:-}" ] || [ -z "${2:-}" ] || [ -z "${3:-}" ]  || [ -z "${4:-}" ] ; then
    usage
    exit 1
fi

user="$1"
db="$2"
host="$3"
sqlfile="$4"

echo "Applying sql script '$sqlfile' to database '$db' on '$host' as user '$user' ..."

PGOPTIONS='--client-min-messages=warning' psql -X -q -1 -v ON_ERROR_STOP=1 --pset pager=off -d "$db" -U "$user"  -h "$host" -f "$sqlfile"

echo "... done"
